# This is a basic workflow to help you get started with Actions

name: Docker Build

# Controls when the action will run. 
on:
  release: 
    types: [published]
  push:
    branches:
      - 'dev'
      - 'master'
  pull_request:
    branches:
      - 'master'
      - 'dev'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      # Setting the defaults up front
      LATEST_NODE: 16
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [16]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - name: Show Env
        run: env
      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          flavor: |
            latest=true
            suffix=-${{matrix.node}}
          images: | 
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}

      - 
        name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Get Date
        id: date
        run: echo "name=date::$(date +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        id: build-push
        uses: docker/build-push-action@v2
        continue-on-error: true
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          file: docker/Dockerfile.nodered 
          build-args: |
            NODE_VERSION=${{ matrix.node }}
            BUILD_DATE=${{ steps.date.outputs.date }}
            BUILD_REF=${{ github.sha }}
            CONTEST_DASHBOARD_VERSION=${{ steps.meta.outpus.tags }}
            TAG_SUFFIX=${{ github.run_number }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
