on:
  push:
    branches:
      - master
    paths-ignore:
      - '.gitignore'

jobs:

  Create-Version-Tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token : ${{ secrets.GITHUB_TOKEN }}
    - run: git config --global user.name 'kd9lsv'
    - run: git config --global user.email 'connor@kd9lsv.me'
    - run: npm version patch -m "[RELEASE] %s"
    - run: git push
    - name: Get Date
      id: date
      run: echo "name=date::$(date +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
    - name: Create an Tag
      uses: simpleactions/create-tag@v1.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        sha: ${{ github.sha }}
        # The tag name
        tag: v${{steps.versioning.outputs.version}}
        # The message
        message: ${{steps.versioning.outputs.version}} Update on ${{steps.date.outputs.date}}
    - name: Generate changelog
      id: changelog
      uses: heinrichreimer/action-github-changelog-generator@v2.3
      with:
          token: ${{ secrets.GITHUB_TOKEN }} 
    - name: Create Release
      uses: ncipollo/release-action@v1
      if: steps.create_tag.outputs.successful
      with:
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
        name: ${{ steps.versioning.outputs.version }}
        tag: ${{ steps.versioning.outputs.version }}
        body: |
          ```bash
          See docker package for updated version ${{steps.versioning.outputs.version}}
          ```
          ${{ steps.changelog.outputs.changelog }}
