on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**/*.yml'
      - '.gitignore'

jobs:

  Create-Version-Tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: master
    - name: Auto Increment Semver Action
      uses: MCKanpolat/auto-semver-action@1.0.9
      id: versioning
      with:
        releaseType: patch
        incrementPerCommit: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Next Release Number
      run: echo ${{ steps.versioning.outputs.version }}
    - name: Generate Changelog
      id: changelog
      uses: jaywcjlove/changelog-generator@main
      if: steps.versioning.outputs.version
      with:
        head-ref: ${{steps.versioning.outputs.version}}
        filter-author: (jaywcjlove|小弟调调™|dependabot\[bot\]|Renovate Bot)
        filter: (^[\s]+?[R|r]elease)|(^[R|r]elease)
    - name: Create Release
      uses: ncipollo/release-action@v1
      if: steps.create_tag.outputs.successful
      with:
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
        name: ${{ steps.versioning.outputs.version }}
        tag: ${{ steps.versioning.outputs.version }}
        body: |
          ```bash
          See docker package for updated version ${{steps.create_tag.outputs.versionNumber}}
          ```
          ${{ steps.changelog.outputs.compareurl }}
          ${{ steps.changelog.outputs.changelog }}
