on: workflow_dispatch
name: Update
jobs:
  package-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: set remote url
      run: git remote set-url --push origin https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
    - name: package-update
      uses: taichi/actions-package-update@master
      env:
        AUTHOR_EMAIL: connor@kd9lsv.me
        AUTHOR_NAME: kd9lsv
        EXECUTE: "true"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LOG_LEVEL: debug
      with:
        args: -u --packageFile package.json --loglevel verbose
    - name: Auto Increment Semver Action
      uses: MCKanpolat/auto-semver-action@latest
      id: versioning
      with:
        releaseType: patch
        incrementPerCommit: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Next Release Number
      run: echo ${{ steps.versioning.outputs.version }}
      
